version: "3"
services:
  server:
    network_mode: host
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=production
    build: ./server
    ports:
      - 8080:8080
    container_name: chat-app-server
  client:
    env_file:
      - ./client/.env
    environment:
      - NODE_ENV=production
    build: ./client
    ports:
      - 80:80
    container_name: chat-app-client
    depends_on:
      - server
